# Computer Vision Use Cases Video Demos 🚀, AGPL-3.0 license

# Configuration file for building the Computer Vision use cases documentation site using MkDocs.
# Provides settings to control site metadata, customize the appearance using the
# Material theme, define the navigation structure, and enable various plugins.

# Site metadata
site_name: Computer Vision Use Cases
site_description: Discover computer vision use cases in retail, transportation, healthcare, manufacturing, agriculture, and more, featuring object detection, segmentation, tracking, and pose estimation with advanced models.
site_url: https://visionusecases.com/
site_author: Muhammad Rizwan Munawar
repo_url: https://github.com/RizwanMunawar/visionusecases
edit_uri: https://github.com/RizwanMunawar/visionusecases/tree/main/docs
repo_name: visionusecases
remote_name: https://github.com/RizwanMunawar/visionusecases/docs
docs_dir: "docs/"
site_dir: "site/"
theme:
  name: material
  language: en
  custom_dir: docs/overrides/
  logo: https://raw.githubusercontent.com/RizwanMunawar/visionusecases/main/docs/assets/vision-usecases-logo.png
  favicon: https://raw.githubusercontent.com/RizwanMunawar/visionusecases/main/docs/assets/vision-usecases.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections
    - content.tabs.link
    - announce.dismiss
markdown_extensions:
  - pymdownx.extra
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
      use_pygments: true
copyright: <a href="https://github.com/RizwanMunawar/visionusecases" target="_blank">© 2024 Computer Vision Use Cases.❤️</a> All rights reserved.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RizwanMunawar/visionusecases
      name: Computer Vision Use Cases
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/muhammadrizwanmunawar/
      name: Muhammad Rizwan Munawar
  manifest: manifest.webmanifest
  robots: robots.txt
  analytics:
    provider: google
    property: G-NQ1EQJ9YVY
extra_css:
  - stylesheets/style.css
extra_javascript:
  - javascript/giscus.js
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
nav:
  - Computer Vision Use Cases:
      - Computer Vision Use Cases: index.md
      - Items segmentation in supermarket using computer vision: usecases/items-segmentation-supermarket-ai.md
      - Segmentation masks with object detection model + SAM2: usecases/segmentation-masks-detect-sam2.md
      - Apple Counting on Conveyor Belt: usecases/apple-counting.md
      - Item Counting in Trolleys for Smart Shopping: usecases/items-counting.md
      - Bread Counting on Conveyor Belt: usecases/bread-counting.md
      - Crowd Density Estimation: usecases/crowd-density-estimation.md
plugins:
  - search:
      lang: en
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            docstring_style: google
            show_root_heading: true
            show_source: true
            separate_signature: true
            line_length: 80
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_inheritance_diagram: true
  - redirects:
      redirect_maps:
        hi/index.md: index.md
        track/index.md: index.md
        segment/index.md: index.md
        count/index.md: index.md
        detect/index.md: index.md
        pose/index.md: index.md
        datasets/index.md: index.md
        count/apple-counting.md: usecases/apple-counting.md
        count/bread-counting.md: usecases/bread-counting.md
        count/items-counting.md: usecases/items-counting.md