name: Docs Deployment

on:
  push:
    branches:
      - main  # Deploy whenever main branch is updated

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install MkDocs and Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-git-authors-plugin mkdocstrings mkdocstrings[python] mkdocs-redirects

      # Step 4: Build MkDocs Site
      - name: Build site
        run: mkdocs build

      # Step 5: Add CNAME file for custom domain
      - name: Add CNAME
        run: echo "visionusecases.com" > site/CNAME

      # Step 6: Upload artifact for Pages deployment
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
