name: Docs Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-git-authors-plugin mkdocstrings mkdocstrings[python] mkdocs-redirects

      - name: Build site
        run: mkdocs build

      - name: Add CNAME
        run: echo "visionusecases.com" > site/CNAME

      # Upload site as artifact using v4 (safe version)
      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the artifact
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./site

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          path: ./site
