name: Deploy Computer Vision UseCases Docs

# Trigger the workflow on push to specific files
on:
  push:
    paths:
      - 'docs/**'  # Trigger when any files in the 'docs' folder are updated
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Compatible Python version for MkDocs

      # Step 3: Install dependencies
      - name: Install MkDocs and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      # Step 4: Build the Docs
      - name: Build MkDocs Site
        run: mkdocs build  # This generates the site into the 'site/' directory

      # Step 5: Deploy Docs
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}  # Use your PAT from secrets
          publish_dir: ./site  # The default directory for MkDocs build
